# Generated by Django 5.2.12 on 2026-04-20 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postulaciones', '0002_postulacion_estado_entrevista'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postulacion',
            options={'ordering': ['-fecha_postulacion']},
        ),
    ]
