# Generated by Django 5.2.12 on 2026-05-30 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulaciones', '0003_alter_postulacion_options'),
        ('vacantes', '0002_vacante_creado_por_alter_vacante_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=255)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('candidato_nombre', models.CharField(max_length=150)),
                ('estado_postulacion', models.CharField(default='aprobado', max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('tipo_contrato', models.CharField(choices=[('indefinido', 'Indefinido'), ('temporal', 'Temporal'), ('por_proyecto', 'Por proyecto')], default='indefinido', max_length=20)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('postulacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='postulaciones.postulacion')),
                ('vacante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='vacantes.vacante')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
