# Generated by Django 5.2.12 on 2026-03-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('area', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField()),
                ('fecha_limite', models.DateField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cerrada', 'Cerrada'), ('pausada', 'Pausada')], max_length=10)),
            ],
        ),
    ]
