# Generated by Django 5.2.12 on 2026-03-20 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='creado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vacantes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacante',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('cerrada', 'Cerrada'), ('pausada', 'Pausada')], default='activa', max_length=10),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
